FROM armhf/debian:jessie
MAINTAINER Lavvy


#configuring custom enviroments 
ENV MINIO_ACCESS_KEY AKIAIOSFODNN7EXAMPLE
ENV MINIO_SECRET_KEY wJalrXUtnFEMI/K7MDENGbPxRfiCYEXAMPLEKEY

# Install packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y install wget
RUN wget https://dl.minio.io/server/minio/release/linux-arm/minio && chmod +x minio
EXPOSE 80 9000
CMD ./minio server ~/Photos
